### ISSUE TITLE
Mispelling in community section

### ISSUE THREAD

**Issue by NotGuyHero** [SWRPDevelopers/swrp.dev-issues#3]
**Describe the bug**

**To Reproduce**
1. Go to 'Community'
2. try to validate a gamerserver that won't query propery

**Expected behavior**
I expected the text to make sense on the error screen

**Screenshots**
it's in the web-discussion channel

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version whatever most recent one is

**Additional context**

**Comment by Alydus** [comment]
Resolved.

Thanks @GuyHero1234 .
